import type { Metadata } from "next";
import { Nunito } from "next/font/google";import "./globals.css";
import ClientProviders from "@/components/ClientProvider";
import GoogleTranslate from "@/components/GoogleTranslate";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${nunito.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GoogleTranslate /> 
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
